### ISSUE TITLE
Feature Request: allow chain information to be encoded into the URL

### ISSUE THREAD

**Issue by chrishobcroft** [komputing/FaucETH#32]
As a user, I would like to be able to load a URL containing encoded chainID e.g. `?chainID=421611` and for this to pre-select the "Arbitrum Rinkeby" network from the drop-down.

![image](https://user-images.githubusercontent.com/2212651/154802718-ad18e282-619c-41b2-ac21-67ad9b86b30f.png)

**Comment by ligi** [comment]
this is already possible ;-)

https://fauceth.komputing.org/?chain=421611
