### ISSUE TITLE
Could not resolve ENS name

### ISSUE THREAD

**Issue by sennett** [komputing/FaucETH#36]
I have just registered sennett.eth on Goeril:  https://goerli.etherscan.io/enslookup-search?search=sennett.eth

When I enter this into the faucet, I get an error "Could not resolve ENS name".

<img width="568" alt="image" src="https://user-images.githubusercontent.com/3783198/159240369-d1e7424a-b40b-440a-9350-b49096b7d80d.png">

<img width="541" alt="image" src="https://user-images.githubusercontent.com/3783198/159240521-7e570d61-dc04-462b-8359-33039b2d398f.png">

**Comment by ligi** [comment]
It's mainnet ENS - otherwise it would defeat the purpose as it would not hold up the people draining the faucet ;-)
but yea - it should be made clear in the UI - ideas welcome!

**Comment by sennett** [comment]
Ah fair enough!  Yeah including that in the message would be great!  I'll see about making a PR.
